# Generated by Django 4.2.5 on 2023-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=3)),
                ('year', models.CharField(max_length=10)),
                ('highest_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('second_highest_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usage_hours_highest_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usage_hours_second_highest_kw', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
