# Generated by Django 4.2.5 on 2023-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berechnung_benutzungsstunden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyUsage_cleaned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('total_energy', models.FloatField()),
                ('highest_kw', models.FloatField()),
                ('second_highest_kw', models.FloatField()),
                ('usage_hours_highest_kw', models.FloatField()),
                ('usage_hours_second_highest_kw', models.FloatField()),
            ],
        ),
    ]
