# Generated by Django 4.2.5 on 2023-10-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berechnung_benutzungsstunden', '0003_remove_energyusage_cleaned_total_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusage',
            name='highest_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='second_highest_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='usage_hours_highest_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='usage_hours_second_highest_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyusage_cleaned',
            name='highest_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyusage_cleaned',
            name='second_highest_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyusage_cleaned',
            name='usage_hours_highest_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyusage_cleaned',
            name='usage_hours_second_highest_kw',
            field=models.FloatField(),
        ),
    ]
