# Generated by Django 4.2.5 on 2023-10-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berechnung_benutzungsstunden', '0006_alter_energyusage_year_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusage',
            name='year_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='energyusage_cleaned',
            name='year_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
