# Generated by Django 4.2.2 on 2024-04-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berechnung_benutzungsstunden', '0008_alter_energyusage_year_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnergyUsage_cleaned',
        ),
    ]
